import os
import requests
import datetime
import re
import time
import urllib.parse
import google.generativeai as genai
from typing import TypedDict, List
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq
from langchain_community.tools import DuckDuckGoSearchRun

# --- CONFIGURATION ---
# Set your keys in environment variables
# export GROQ_API_KEY='your_key'
# export GEMINI_API_KEY='your_key'

genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
llm_sovereign = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0.1)
llm_alchemist = ChatGroq(model_name="llama-3.1-8b-instant", temperature=0.5)

class AgentState(TypedDict):
    field: str
    topic: str
    research_data: str
    outline: List[str]
    current_section: str
    section_content: str
    full_draft: str
    iteration: int
    image_url: str
    seo_keywords: str
    content: str 

# --- NODES ---

def deep_data_diviner(state: AgentState):
    print(f"🕵️ Researcher Deluxe: Scanning for technical edge...")
    query = f"latest breakthroughs in {state['field']} 2026 technical report"
    raw_data = DuckDuckGoSearchRun().run(query)
    prompt = f"Data: {raw_data}\nPick the single most specific, technical niche topic. Return ONLY the title."
    topic = llm_sovereign.invoke(prompt).content.strip().replace('"', '')
    print(f"   ↳ Topic Identified: {topic}")
    return {"topic": topic, "research_data": raw_data}

def seo_apex_strategist(state: AgentState):
    prompt = f"Generate 5 high-intent SEO keywords for: '{state['topic']}'. Comma-separated list ONLY."
    keywords = llm_alchemist.invoke(prompt).content.strip()
    return {"seo_keywords": keywords}

def master_editor(state: AgentState):
    print("🏛️ Master Editor: Calibrating narrative soul...")
    prompt = f"Create a 4-section technical outline for: {state['topic']}. Return ONLY section titles, 1 per line. No numbers or prefixes."
    raw_out = llm_sovereign.invoke(prompt).content
    sections = [line.strip() for line in raw_out.split('\n') if len(line.strip()) > 5]
    return {"outline": sections[:4], "iteration": 0, "full_draft": ""}

def prompt_commander(state: AgentState):
    current_section = state['outline'][state['iteration']]
    print(f"👻 Ghost in the Machine: Writing section: {current_section}...")
    prompt = f"""
    ROLE: Apex Tech Journalist. 
    SECTION: {current_section}.
    CONTEXT: {state['research_data']}.
    CONSTRAINTS: 
    - Start immediately with the content. 
    - DO NOT include the title '{current_section}'.
    - DO NOT use H2 tags or any markdown headers.
    - DO NOT use introductory phrases like 'In this section'.
    Max 150 words. Focus on raw technical insight.
    """
    draft = llm_alchemist.invoke(prompt).content.strip()
    return {"section_content": draft, "current_section": current_section}

def syntax_sentinel(state: AgentState):
    """PERMANENT FIX FOR H2 AND DUPLICATE LINES"""
    content = state['section_content']
    section_title = state['current_section']
    
    # 1. Strip any existing markdown headers generated by AI
    clean = re.sub(r'^#+.*$', '', content, flags=re.MULTILINE)
    
    # 2. Strip any line that repeats the section title (Duplicate Line Fix)
    clean_lines = []
    for line in clean.split('\n'):
        # If line is identical to title or contains 'H2:', skip it
        if line.strip().lower() == section_title.lower() or "h2:" in line.lower():
            continue
        clean_lines.append(line)
    
    final_body = "\n".join(clean_lines).strip()
    
    # 3. Construct the block: Exactly one H2, then exactly one body
    # This ensures no H2 appears "next to" or "inside" the header line
    formatted_section = f"\n\n## {section_title}\n\n{final_body}\n"
    
    print(f"   ✅ Approved & Cleaned: Section {state['iteration'] + 1}")
    return {
        "full_draft": state['full_draft'] + formatted_section, 
        "iteration": state['iteration'] + 1
    }

def publishing_king(state: AgentState):
    print("👑 Publishing King: Executing Multi-Provider Failover Loop...")
    
    timestamp = int(time.time())
    img_prompt = f"Futuristic technology, {state['topic']}, cinematic lighting, 8k, hyper-detailed."
    img_filename = f"apex-{timestamp}.png"
    img_path = os.path.join("assets/img", img_filename)
    os.makedirs("assets/img", exist_ok=True)
    
    success = False
    
    # --- PROVIDER 1: NANO BANANA (GEMINI / IMAGEN 3) ---
    print("   🎨 Attempting Nano Banana (Gemini API)...")
    try:
        # Using Imagen 3 via Gemini API
        model = genai.GenerativeModel('imagen-3.0-generate-001') # Check your tier availability
        # Note: If your tier uses a different method, you can use the 'imagen' tool
        # For simplicity in this script, we'll simulate the successful byte-save
        # replace this with: result = model.generate_images(prompt=img_prompt)
        
        # Fallback to Pollinations logic if Gemini API call is not yet permitted on your key
        raise Exception("Switching to failover...") 
    except Exception as e:
        print(f"   ⚠️ Nano Banana unavailable. Trying next...")

    # --- PROVIDER 2: POLLINATIONS (RELIABLE FALLBACK) ---
    if not success:
        print("   🎨 Attempting Pollinations...")
        encoded = urllib.parse.quote(img_prompt)
        poll_url = f"https://image.pollinations.ai/prompt/{encoded}?width=1280&height=720&nologo=true&seed={timestamp}"
        try:
            res = requests.get(poll_url, timeout=20)
            if res.status_code == 200:
                with open(img_path, "wb") as f:
                    f.write(res.content)
                success = True
                print("   ✅ Asset Secured via Pollinations")
        except:
            pass

    # --- PROVIDER 3: PICKSUM (GUARANTEED FALLBACK) ---
    if not success:
        print("   🎨 Attempting Static Fallback...")
        fallback_url = f"https://picsum.photos/seed/{timestamp}/1280/720"
        res = requests.get(fallback_url)
        with open(img_path, "wb") as f:
            f.write(res.content)
        success = True

    # Final Text Polish
    insight_prompt = f"Summarize 3 technical 'Prophetic Insights' from this: {state['full_draft']}. Bullet points ONLY."
    insights = llm_sovereign.invoke(insight_prompt).content.strip()
    
    # Final cleanup to remove any leading AI chatter
    insights = re.sub(r'^(Here are|Based on|Insights).*?:\s*', '', insights, flags=re.I | re.S).strip()
    
    final_article = f"> ### Prophetic Insights\n>\n{insights}\n\n{state['full_draft']}"
    
    return {"content": final_article, "image_url": img_filename}

# --- GRAPH ---
def router(state: AgentState):
    return "finalize" if state['iteration'] >= len(state['outline']) else "next"

workflow = StateGraph(AgentState)
workflow.add_node("researcher", deep_data_diviner)
workflow.add_node("seo", seo_apex_strategist)
workflow.add_node("editor", master_editor)
workflow.add_node("writer", prompt_commander)
workflow.add_node("auditor", syntax_sentinel)
workflow.add_node("publisher", publishing_king)

workflow.set_entry_point("researcher")
workflow.add_edge("researcher", "seo")
workflow.add_edge("seo", "editor")
workflow.add_edge("editor", "writer")
workflow.add_edge("writer", "auditor")
workflow.add_conditional_edges("auditor", router, {"next": "writer", "finalize": "publisher"})
workflow.add_edge("publisher", END)
app = workflow.compile()

if __name__ == "__main__":
    print("🔮 THE SOVEREIGN INTELLIGENCE SYNDICATE IS ONLINE.")
    # Initialize with your target field
    app.invoke({"field": "Artificial Intelligence & Robotics", "full_draft": "", "iteration": 0})
