import os
import requests
import re
import time
import urllib.parse
from google import genai  # Required: pip install google-genai
from typing import TypedDict, List
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq
from langchain_community.tools import DuckDuckGoSearchRun

# --- CONFIGURATION ---
# Initialize the Gemini Client for Nano Banana (Gemini API)
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

llm_sovereign = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0.1)
llm_alchemist = ChatGroq(model_name="llama-3.1-8b-instant", temperature=0.5)

class AgentState(TypedDict):
    field: str
    topic: str
    research_data: str
    outline: List[str]
    current_section: str
    section_content: str
    full_draft: str
    iteration: int
    image_url: str
    seo_keywords: str
    content: str 

# --- NODES ---

def deep_data_diviner(state: AgentState):
    print(f"🕵️ Researcher: Scouting technical niche...")
    query = f"latest {state['field']} breakthroughs 2026"
    raw_data = DuckDuckGoSearchRun().run(query)
    prompt = f"Data: {raw_data}\nIdentify the single most technical niche topic. Return ONLY the title."
    topic = llm_sovereign.invoke(prompt).content.strip().replace('"', '')
    return {"topic": topic, "research_data": raw_data}

def seo_apex_strategist(state: AgentState):
    prompt = f"Provide 5 SEO keywords for '{state['topic']}'. Comma-separated ONLY."
    keywords = llm_alchemist.invoke(prompt).content.strip()
    return {"seo_keywords": keywords}

def master_editor(state: AgentState):
    print("🏛️ Master Editor: Structuring narrative...")
    prompt = f"Create a 4-section technical outline for: {state['topic']}. Return ONLY section titles, 1 per line."
    raw_out = llm_sovereign.invoke(prompt).content
    sections = [line.strip() for line in raw_out.split('\n') if len(line.strip()) > 5]
    return {"outline": sections[:4], "iteration": 0, "full_draft": ""}

def prompt_commander(state: AgentState):
    current_section = state['outline'][state['iteration']]
    print(f"👻 Writer: Drafting {current_section}...")
    prompt = f"""
    SECTION: {current_section}
    CONTEXT: {state['research_data']}
    CONSTRAINTS: 
    - No headers or titles. 
    - Start immediately with the content.
    - No introductory phrases like 'This section discusses'.
    """
    draft = llm_alchemist.invoke(prompt).content.strip()
    return {"section_content": draft, "current_section": current_section}

def syntax_sentinel(state: AgentState):
    """
    PERMANENT SOLUTION: Prevents H2 tag artifacts and duplicate header lines.
    """
    content = state['section_content']
    section_title = state['current_section'].strip()
    
    # 1. Strip ALL existing markdown headers or "H2:" markers generated by the AI
    clean = re.sub(r'(?i)^#+.*$', '', content, flags=re.MULTILINE)
    clean = re.sub(r'(?i)^h2:.*$', '', clean, flags=re.MULTILINE)
    
    # 2. Filter out duplicate lines
    lines = clean.split('\n')
    filtered_lines = [l for l in lines if l.strip().lower() != section_title.lower() and l.strip()]
    
    final_body = "\n\n".join(filtered_lines)
    
    # 3. Reconstruct with clean markdown header
    formatted_section = f"\n\n## {section_title}\n\n{final_body}\n"
    
    return {
        "full_draft": state['full_draft'] + formatted_section, 
        "iteration": state['iteration'] + 1
    }

def publishing_king(state: AgentState):
    print("👑 Publisher: Executing Image Failover (Gemini -> Pollinations -> Picsum)...")
    
    timestamp = int(time.time())
    img_prompt = f"Cinematic tech visual for {state['topic']}, 8k, futuristic."
    img_filename = f"apex-{timestamp}.png"
    img_path = os.path.join("assets/img", img_filename)
    os.makedirs("assets/img", exist_ok=True)
    
    success = False
    
    # --- PROVIDER 1: NANO BANANA (GEMINI / IMAGEN 3) ---
    print("   🎨 Attempting Nano Banana...")
    try:
        # FIX: Updated to 'generate_images' and added GenerateImagesConfig
        response = client.models.generate_images(
            model='imagen-3.0-generate-001',
            prompt=img_prompt,
            config=genai.types.GenerateImagesConfig(
                number_of_images=1,
            )
        )
        if response.generated_images:
            with open(img_path, "wb") as f:
                f.write(response.generated_images[0].image_bytes)
            success = True
            print("   ✅ Image saved via Nano Banana")
    except Exception as e:
        print(f"   ⚠️ Nano Banana skipped: {e}")

    # --- PROVIDER 2: POLLINATIONS (AI FALLBACK) ---
    if not success:
        print("   🎨 Attempting Pollinations...")
        encoded = urllib.parse.quote(img_prompt)
        poll_url = f"https://image.pollinations.ai/prompt/{encoded}?nologo=true&seed={timestamp}"
        try:
            res = requests.get(poll_url, timeout=20, headers={"User-Agent": "Mozilla/5.0"})
            if res.status_code == 200:
                with open(img_path, "wb") as f:
                    f.write(res.content)
                success = True
                print("   ✅ Image saved via Pollinations")
        except: pass

    # --- PROVIDER 3: PICKSUM (STATIC FALLBACK) ---
    if not success:
        print("   🎨 Attempting Static Fallback...")
        res = requests.get(f"https://picsum.photos/seed/{timestamp}/1280/720")
        with open(img_path, "wb") as f:
            f.write(res.content)
        success = True

    return {"content": state['full_draft'], "image_url": img_filename}

# --- GRAPH ---
def router(state: AgentState):
    return "finalize" if state['iteration'] >= len(state['outline']) else "next"

workflow = StateGraph(AgentState)
workflow.add_node("researcher", deep_data_diviner)
workflow.add_node("seo", seo_apex_strategist)
workflow.add_node("editor", master_editor)
workflow.add_node("writer", prompt_commander)
workflow.add_node("auditor", syntax_sentinel)
workflow.add_node("publisher", publishing_king)

workflow.set_entry_point("researcher")
workflow.add_edge("researcher", "seo")
workflow.add_edge("seo", "editor")
workflow.add_edge("editor", "writer")
workflow.add_edge("writer", "auditor")
workflow.add_conditional_edges("auditor", router, {"next": "writer", "finalize": "publisher"})
workflow.add_edge("publisher", END)
app = workflow.compile()

if __name__ == "__main__":
    app.invoke({"field": "AI & Robotics", "full_draft": "", "iteration": 0})
